type Item = { q: string; a: string };
const answer = (lead: string, detail: string): string => `${lead} ${detail}`;
export const faqGroups: { theme: string; items: Item[] }[] = [
  { theme: "Fees & cost", items: [
    { q: "How much does an AI course cost in India in 2026?", a: answer("AI courses range from ₹0 to ₹5,00,000+ in India in 2026.", "Free university and open courses sit at one end; structured specialist cohorts commonly occupy the middle; executive credentials and placement-heavy bootcamps sit at the top. Compare the total payable amount, support and likely completion—not only the advertised fee. Provider-specific figures on this page remain marked [VERIFY] until checked against current public sources.") },
    { q: "What is the average fee for an AI ML course?", a: answer("There is no honest single average because the category mixes short videos, cohorts, degrees and executive certificates.", "A useful planning range is ₹50,000–₹2,50,000 for a structured, job-oriented AI/ML program, while self-paced foundations can cost far less. Choose a comparable format first, then compare total cost, live hours, reviewed projects, credential value and career support within that band.") },
    { q: "Which is the cheapest AI course in India?", a: answer("The cheapest credible route is free.", "NPTEL, SWAYAM, fast.ai, Hugging Face and MOOC audit modes can build strong foundations without tuition. A certificate or exam may cost extra [VERIFY]. Free is best when you can create your own sequence, deadlines and portfolio; otherwise, a low-fee cohort may have a better completion-adjusted cost despite its higher sticker price.") },
    { q: "Are expensive AI courses better?", a: answer("No—higher price does not automatically mean better AI instruction.", "Premium fees often buy a recognised credential, placement operations, alumni access or senior peer networks rather than a deeper syllabus. Those are legitimate benefits when they match your goal. Compare curriculum freshness, human feedback, live hours and outcome evidence separately so you pay only for support or signalling you cannot provide yourself.") },
    { q: "How much does an IIT AI course cost?", a: answer("The fee depends on the specific institute, course type and level of IIT involvement.", "Executive programs commonly occupy premium bands, while full degrees use term-based pricing and short co-branded offerings may follow another structure entirely. Check the issuing institution, teaching responsibility, live hours and current official fee page. Any amount not publicly verified should remain [VERIFY], not be inferred from a similar program.") },
    { q: "What is the fee of an online AI course vs. an offline one?", a: answer("Online learning is usually cheaper in total cost, even when tuition looks similar.", "Offline study can add relocation, rent, commuting, equipment and lost work hours. Online formats range from free audits to premium live cohorts; offline fees also vary by city and centre. Build a six-month total-cost comparison using your actual travel and living assumptions, labelled [ILLUSTRATIVE], before choosing.") },
    { q: "Do AI course fees include GST?", a: answer("Not always; ask for the total payable amount including GST in writing.", "Some providers show tax-inclusive pricing while others add applicable tax at checkout or in the invoice. Do not calculate from a headline alone. Confirm the tax treatment, invoice issuer, instalment total and whether financing charges attract additional tax. The commonly cited rate and its applicability should be [VERIFY] against current guidance.") },
    { q: "What hidden costs should I budget for?", a: answer("Budget for finance charges, tools, cloud usage, exams, travel and your own time.", "Other possible costs include laptop upgrades, GPU or API credits, proctored certificates, placement add-ons, resubmission fees and lost income from fixed class hours. Ask which project infrastructure is included. Add each cost to the real-cost formula and divide by your realistic completion probability before comparing programs.") },
    { q: "What is the LogicMojo AI & ML Course fee?", a: answer("The stated LogicMojo AI & ML Course fee is ₹87,000.", "The current offer specified for this guide is 15% off for the first 15 enrolments, producing a fee of ₹73,950. Re-check that the seat-limited offer is still active before each republication, and confirm GST treatment, EMI total, inclusions, refund terms and batch details in writing because those details remain [VERIFY].") },
    { q: "Do AI courses offer student or early-bird discounts?", a: answer("Many providers advertise student, seasonal, referral or early-bird pricing.", "Treat a discount as real only when the base price, eligibility, expiry, total payable amount and refund implications are written down. A resetting timer is not evidence of scarcity. Compare the discounted upfront price with the total under EMI, and never let a same-call deadline replace curriculum and policy checks.") },
  ]},
  { theme: "EMI, discounts & refunds", items: [
    { q: "Is EMI available for AI courses?", a: answer("EMI is widely available for paid AI programs, but terms differ.", "It may be a bank-card conversion or a separate education loan from an NBFC. Before signing, identify the lender, annual percentage rate, processing charge, tenure, late-payment consequences and total of all instalments. The provider’s cancellation policy and the lender’s agreement are separate obligations, so read both.") },
    { q: "Is no-cost EMI really free?", a: answer("No-cost EMI is not automatically cost-free.", "Interest may be subsidised by the provider, offset by removing an upfront discount, or accompanied by processing charges and taxes. Ask for two written numbers: the best same-day upfront total and the total across every instalment. The difference reveals the effective financing cost even when the statement shows no interest line.") },
    { q: "What happens to my EMI if I stop attending?", a: answer("Your EMI usually continues after you stop attending.", "When a lender has already paid the provider, your repayment duty is governed by the loan agreement, not classroom attendance. A course cancellation does not automatically close the loan. Check refund timing, foreclosure charges, deferral options and credit-reporting consequences before enrolling, especially when the repayment term exceeds the course duration.") },
    { q: "Can I get a refund if the course isn't as promised?", a: answer("A refund is possible only under the provider’s written policy and applicable consumer rights.", "Save the sales page, syllabus, emails, invoice and promised inclusions. Note the exact cut-off date and permitted deductions. Raise discrepancies in writing promptly. Do not assume dissatisfaction alone triggers a refund, and verify current legal or regulatory remedies before citing them as guaranteed protection.") },
    { q: "Can I negotiate AI course fees?", a: answer("You can ask, because many providers use variable offers, but there is no guaranteed discount.", "Request student, group, employer, referral or upfront-payment pricing without inventing urgency. Compare the final written total rather than verbal percentages. A lower fee is useful only if the same curriculum, support, certificate, refund rights and placement services remain included after the discount.") },
    { q: "Does my employer reimburse AI courses?", a: answer("Some employers reimburse approved AI learning through L&D budgets.", "Approval usually depends on business relevance, provider documentation, successful completion and sometimes a service commitment. Submit the course name, curriculum, duration, fee, credential issuer and manager justification before paying. Confirm whether reimbursement covers GST, exams and tools, and whether repayment is required if you leave the company.") },
  ]},
  { theme: "Duration", items: [
    { q: "How long does an AI course take?", a: answer("AI courses can take several weeks to several years depending on the outcome.", "Short literacy tracks often take 4–12 weeks, specialist career programs commonly take 5–12 months, and formal degrees take years. Published duration assumes a weekly pace; translate it into your available hours. A shorter course is not faster if you repeatedly pause or cannot complete its projects.") },
    { q: "Can I finish an AI course in 3 months?", a: answer("Yes, if the scope is narrow or you already have programming and maths foundations.", "Three months can cover literacy, a targeted GenAI skill or an intensive foundation, but it is rarely enough for a complete beginner to build broad ML, deep-learning, deployment and interview capability while working full time. Judge the promised outcomes against live hours, assignments and project depth rather than the calendar label.") },
    { q: "How many hours per week does an AI course need?", a: answer("Plan 10–15 hours a week for a serious career-track program.", "That usually includes classes, coding, reading, debugging and portfolio work. Under six hours can suit literacy or focused self-paced modules, but a live cohort may outrun you. Block the hours in your real calendar for the next six months and account for work peaks before paying.") },
    { q: "Short certification or long PG program?", a: answer("Choose a short certification for a specific skill gap and a long PG program for breadth or credential value.", "If you already code and need RAG, cloud ML or model deployment, a compact course can be efficient. If HR recognition, academic progression or structured foundations matter, a longer program may justify its cost. Compare completion risk and opportunity cost alongside tuition.") },
    { q: "Can I learn AI while working full time?", a: answer("Yes, provided the schedule matches your predictable weekly capacity.", "Weekend or evening cohorts work when recordings, deferrals and doubt support cover unavoidable work conflicts. Self-paced courses offer flexibility but demand more discipline. Protect fixed practice blocks, avoid overlapping major work releases, and plan for projects after class; attendance alone does not create employable evidence.") },
  ]},
  { theme: "Eligibility", items: [
    { q: "Who is eligible for an AI course?", a: answer("Eligibility ranges from open entry to degree and experience requirements.", "Free and introductory courses usually accept anyone; career cohorts may expect graduation, aptitude or basic coding; executive programs often require work experience. Verify the exact public criteria for each program. More important than formal eligibility is readiness in Python, data handling and mathematical intuition for the promised pace.") },
    { q: "Can I do an AI course after 12th?", a: answer("Yes, but foundations or a recognised degree path are usually the sensible first step.", "Build Python, SQL, statistics and small projects before taking a large loan for a job-oriented bootcamp. Some online degrees provide 12th-pass qualifier routes [VERIFY current rules]. At this stage, low-cost exploration protects your budget while showing whether you enjoy sustained coding work.") },
    { q: "Can a non-IT graduate join an AI course?", a: answer("Yes—non-IT graduates can learn applied AI with sufficient onboarding and practice.", "Look for a bridge module in Python, SQL, statistics and problem-solving, and budget one or two extra months before advanced topics. Domain experience in finance, healthcare, manufacturing or operations can become an advantage when paired with technical execution. Avoid programs that hide prerequisites behind broad ‘no coding needed’ language.") },
    { q: "Do I need coding before starting?", a: answer("Coding is not required for AI literacy, but it is required for AI engineering.", "A career-track learner should become comfortable with basic Python, debugging and data manipulation before deep-learning modules. If the course accepts beginners, verify that prerequisite onboarding is included and supported. Spending a few weeks on foundations can prevent expensive frustration in the first live cohort month.") },
    { q: "Do I need maths?", a: answer("You need mathematical intuition for applied AI, not necessarily advanced proofs.", "Linear algebra, probability, statistics and gradients help you choose metrics, spot leakage and understand training behaviour. Research roles demand more depth. A practical course should connect maths to code and model decisions; a syllabus that avoids it entirely may leave you unable to diagnose why a model fails.") },
    { q: "Is a CS degree necessary for AI jobs?", a: answer("A CS degree is not universally necessary for applied AI jobs.", "Hiring teams often care more about coding, systems thinking, evaluation and credible projects, although some companies retain degree filters and research roles may expect advanced qualifications. A course certificate cannot replace demonstrated capability. Build public work that explains the problem, trade-offs, metrics, failures and deployment choices.") },
  ]},
  { theme: "Placements & careers", items: [
    { q: "Do AI courses provide placement?", a: answer("Most courses provide placement assistance, not a guaranteed job.", "Assistance may include resume review, mock interviews, referrals, job boards or hiring events. Ask for every service item, eligibility condition and outcome denominator: enrolled, completed, eligible, interviewed and placed over a defined period. Do not treat logos or isolated salary stories as evidence of a repeatable result.") },
    { q: "What does \"job assistance\" actually include?", a: answer("Job assistance is a bundle of services whose scope must be written down.", "Useful components include portfolio review by a practitioner, role-specific resume feedback, repeated mock interviews, application strategy, verified referrals and interview debriefs. Ask how long support lasts, whether access depends on grades and who delivers it. A generic job board alone has limited value.") },
    { q: "What salary can I expect after an AI course in India?", a: answer("No course can guarantee a salary, and the honest range depends on role, city and prior experience.", "A career switcher’s result is shaped by existing engineering depth, portfolio evidence, interview performance and market conditions. Use current salary reports and job postings with clear dates and sample definitions [VERIFY]. Treat provider figures without sources or denominators as marketing, not a personal forecast.") },
    { q: "Can a fresher get an AI job after a course?", a: answer("Yes, but a certificate alone is rarely enough for a fresher.", "Entry roles reward Python, SQL, data work, model evaluation and evidence that you can finish projects independently. Internships, open-source work and strong case studies can bridge the experience gap. Apply to adjacent analyst and software roles as well as titles labelled AI, because first-role scope matters more than title.") },
    { q: "How long after finishing does it take to get an AI job?", a: answer("There is no reliable universal timeline.", "Plan a focused application period of several months rather than expecting placement at graduation. Your speed depends on readiness, location, notice period, role flexibility, referrals and interview volume. Start portfolio review and mock interviews before the course ends, track conversion at each stage, and adjust the bottleneck rather than sending identical applications indefinitely.") },
    { q: "Do Indian employers value online AI certificates?", a: answer("Employers value credible online certificates mainly as supporting evidence, not proof of job readiness.", "A recognised issuer can help with HR screening, internal mobility or reimbursement, while technical teams will inspect what you built and how you reason. The strongest certificate is paired with original projects, clear documentation and the ability to defend data, evaluation, cost and deployment decisions.") },
  ]},
  { theme: "Certification & value", items: [
    { q: "Are free AI courses with certificates worth it?", a: answer("Yes, especially for foundations, exploration and a low-risk first credential.", "The certificate’s signalling power may be modest, but the learning can be excellent. Choose a recognised source, complete assessments and turn the material into an original project. Pay an exam fee only when the credential helps a specific application, reimbursement or academic goal; otherwise the capability is the valuable part.") },
    { q: "Which AI certification is most valued in India?", a: answer("There is no single most-valued AI certification across Indian roles.", "Cloud certificates can help platform-specific positions, university credentials can help HR filters, and specialist programs can support applied portfolios. Start from target job descriptions and count repeated requirements. The right certification is the least expensive credible signal that closes a real gap alongside demonstrable work.") },
    { q: "Is an AI course worth the fee in 2026?", a: answer("An AI course is worth its fee when it buys support you will use and can realistically complete.", "Content itself is abundant and often free; paid value comes from structure, human feedback, credential recognition and career operations. Compute total real cost, run the 15-point checklist and compare the result with your expected use—not an advertised salary. Completion and portfolio quality determine ROI more than price.") },
  ]},
];
