// Master comparison table.
// "Verified" = figure published on the provider's own public page and re-checked.
// "Provider-reported" = claim made by the provider that this guide has not independently confirmed.
// "[VERIFY]" = not publicly published at the time of writing; ask the provider in writing.

export const masterComparison = {
  headers: [
    "Course / Program",
    "Fees (₹)",
    "Duration",
    "Eligibility",
    "Learning Mode",
    "Curriculum",
    "Projects",
    "Mentorship",
    "Placement Support",
    "Certification",
    "Value for Money",
  ],
  rows: [
    [
      "NPTEL / SWAYAM AI & ML courses",
      "₹0 · exam certificate fee extra [VERIFY]",
      "4–12 weeks per course",
      "Open to all",
      "Self-paced online",
      "Academic ML, some DL (Verified: public course pages)",
      "Assignments, few applied projects",
      "None",
      "None",
      "Institute exam certificate",
      "Highest content-per-rupee; no support",
    ],
    [
      "fast.ai — Practical Deep Learning",
      "₹0 (Verified)",
      "8–10 weeks",
      "Some coding experience",
      "Self-paced online",
      "Applied DL, partial GenAI",
      "Build-first notebooks",
      "Community forum only",
      "None",
      "None",
      "Best free route to shipping models",
    ],
    [
      "Hugging Face courses (NLP, LLM, Agents)",
      "₹0 (Verified)",
      "4–8 weeks each",
      "Python basics",
      "Self-paced online",
      "GenAI, LLMs, agents (current stack)",
      "Hands-on notebooks",
      "Community only",
      "None",
      "Completion certificate",
      "Most current GenAI material at zero fee",
    ],
    [
      "Udemy AI/ML courses",
      "₹499–₹3,999 · list prices vary [VERIFY]",
      "20–60 hours",
      "None",
      "Self-paced recorded",
      "ML plus partial DL/GenAI, quality varies by instructor",
      "Build-along projects",
      "None",
      "None",
      "Udemy certificate",
      "Cheapest structured content; no feedback",
    ],
    [
      "Google Cloud / AWS / Azure AI tracks",
      "₹0–₹30,000 · exam fee separate [VERIFY]",
      "4–12 weeks",
      "None to intermediate",
      "Self-paced online",
      "Cloud ML, MLOps, GenAI services",
      "Labs, not portfolio projects",
      "None",
      "None",
      "Vendor certification",
      "Strong HR signal for cloud roles",
    ],
    [
      "DeepLearning.AI (Coursera)",
      "Subscription ₹X,XXX/month [VERIFY]",
      "3–6 months",
      "Python, basic maths",
      "Self-paced online",
      "ML, DL, GenAI fundamentals",
      "Guided labs",
      "None (graded quizzes)",
      "None",
      "Specialization certificate",
      "Best conceptual grounding per rupee",
    ],
    [
      "IBM AI Engineering (Coursera)",
      "Subscription ₹X,XXX/month [VERIFY]",
      "4–6 months",
      "None stated",
      "Self-paced online",
      "ML, DL, partial GenAI",
      "Capstone project",
      "None",
      "None",
      "Brand professional certificate",
      "Entry portfolio plus a recognised badge",
    ],
    [
      "PW Skills / GUVI entry programs",
      "₹XX,XXX [VERIFY]",
      "5–12 months",
      "Graduation / final year",
      "Live + recorded",
      "ML, DL, partial GenAI [VERIFY]",
      "Cohort projects [VERIFY]",
      "Limited live support [VERIFY]",
      "Provider-reported job assistance [VERIFY]",
      "Provider certificate",
      "Low fee with some structure",
    ],
    [
      "Udacity Nanodegrees",
      "Subscription ₹XX,XXX/month [VERIFY]",
      "3–6 months",
      "Python basics",
      "Self-paced + human reviews",
      "ML, DL, partial GenAI",
      "Reviewed projects",
      "Project reviewers",
      "Provider-reported career services [VERIFY]",
      "Nanodegree certificate",
      "Human code review at a mid fee",
    ],
    [
      "LogicMojo AI & ML Course",
      "₹87,000 · ₹73,950 for the first 15 enrolments (Verified: LogicMojo course page; GST treatment [VERIFY])",
      "[VERIFY: months]",
      "Graduation + basic aptitude; prerequisite onboarding [VERIFY]",
      "Live online cohort with recordings",
      "Python → ML → DL → NLP/Transformers → GenAI: prompting, LLMs, RAG, LangChain, vector DBs, fine-tuning, agents (Provider-reported [VERIFY current syllabus])",
      "Real-world projects [VERIFY count and briefs]",
      "Live mentor-led cohort + doubt support [VERIFY SLA]",
      "Interview prep, resume and career guidance, job assistance — not a guarantee (Provider-reported; see logicmojo.com/success-story)",
      "Provider certificate",
      "Full-stack AI capability without a credential premium",
    ],
    [
      "Intellipaat / Simplilearn / Great Learning premium",
      "₹1,50,000–₹3,50,000 [VERIFY per program]",
      "7–18 months",
      "Graduation [VERIFY]",
      "Live online / hybrid",
      "ML, DL, GenAI breadth [VERIFY depth]",
      "Capstones",
      "Mentor sessions [VERIFY frequency]",
      "Provider-reported career services [VERIFY]",
      "University or partner-branded certificate",
      "Credential value for HR filters",
    ],
    [
      "Scaler / offline premium bootcamps",
      "₹2,50,000–₹4,00,000 [VERIFY]",
      "11–18 months",
      "Working professionals / graduates [VERIFY]",
      "Live online or classroom",
      "CS fundamentals plus AI/ML modules",
      "Multiple projects",
      "Structured mentorship [VERIFY]",
      "Provider-reported placement infrastructure [VERIFY denominators]",
      "Provider certificate",
      "Placement machinery first; highest fee",
    ],
    [
      "IIT / IIM / IISc executive programs",
      "₹1,50,000–₹5,00,000+ [VERIFY]",
      "6–12 months",
      "Work experience / graduation [VERIFY]",
      "Online + campus immersion",
      "AI often part of broader analytics content",
      "Limited",
      "Faculty sessions",
      "Limited / networking",
      "Institute certificate",
      "Prestige and network, not engineering depth",
    ],
  ],
};
