export const VERIFIED_ON = "[INSERT DATE — verification date]";
export const LAST_UPDATED = "[INSERT DATE]";

export const feeSpectrum = {
  headers: [
    "Fee Band (₹)",
    "What Sits Here",
    "What You Typically Get",
    "Typical Duration",
    "Who It Suits",
  ],
  rows: [
    [
      "₹0",
      "NPTEL/SWAYAM, MOOC audits, Kaggle Learn, Hugging Face, fast.ai, YouTube",
      "World-class content; no structure, no code review, no credential (paid certificate optional)",
      "Self-paced",
      "Self-directed learners with time and discipline",
    ],
    [
      "₹500–₹5,000",
      "Udemy courses, single MOOC certificates",
      "Structured recorded content, build-along projects",
      "20–60 hours",
      "Topic top-ups, first exposure",
    ],
    [
      "₹5,000–₹40,000",
      "PW Skills, GUVI, entry bootcamps, vendor certification paths",
      "Structured curriculum, community, some live support, entry projects, certificate",
      "3–8 months",
      "Students, budget-constrained beginners",
    ],
    [
      "₹40,000–₹1,20,000",
      "Specialist AI/ML programs (LogicMojo sits here at ₹87,000), mid-tier bootcamps",
      "Live mentorship, full-stack curriculum, real projects, interview prep, job assistance",
      "5–9 months",
      "Working professionals and switchers buying capability per rupee",
    ],
    [
      "₹1,20,000–₹2,50,000",
      "upGrad, Great Learning, Simplilearn, Intellipaat premium variants",
      "University/brand credential, career services, moderate-to-good depth",
      "7–18 months",
      "Credential-driven learners, employer-funded professionals",
    ],
    [
      "₹2,50,000–₹5,00,000+",
      "Scaler, IIT/IIM/IISc executive programs, offline premium bootcamps",
      "Placement infrastructure or elite branding; AI often part of a broader program",
      "6–18 months",
      "Placement-first or prestige-first buyers",
    ],
  ],
};

export const table1 = {
  headers: [
    "Program Category",
    "Fee Range (₹)",
    "Typical Duration",
    "Format",
    "Certificate Type",
    "Placement / Job Assistance",
    "Verified On",
  ],
  rows: [
    [
      "Free MOOCs & NPTEL",
      "₹0 (certificate ₹1,000–₹4,000 optional [VERIFY])",
      "4–16 weeks per course",
      "Self-paced online",
      "Completion / NPTEL exam certificate",
      "None",
      "[INSERT]",
    ],
    [
      "Short online certifications",
      "₹3,000–₹40,000",
      "4–12 weeks",
      "Self-paced / hybrid",
      "Provider certificate",
      "Rarely",
      "[INSERT]",
    ],
    [
      "Vendor certifications (Google, AWS, Azure, IBM, NVIDIA)",
      "₹0–₹30,000 (exam fee separate [VERIFY])",
      "4–12 weeks",
      "Self-paced",
      "Vendor certification",
      "None",
      "[INSERT]",
    ],
    [
      "Specialist AI/ML programs (e.g., LogicMojo)",
      "₹40,000–₹1,20,000",
      "5–9 months",
      "Live online cohort",
      "Provider certificate",
      "Job assistance / interview preparation",
      "[INSERT]",
    ],
    [
      "Bootcamps (online, job-oriented)",
      "₹50,000–₹4,00,000",
      "6–18 months",
      "Live online cohort",
      "Provider certificate",
      "Placement support, sometimes ISA",
      "[INSERT]",
    ],
    [
      "University-affiliated PG programs",
      "₹1,50,000–₹3,50,000",
      "7–18 months",
      "Online / hybrid",
      "University PG certificate",
      "Career services",
      "[INSERT]",
    ],
    [
      "IIT / IIM / IISc executive programs",
      "₹1,50,000–₹5,00,000+",
      "6–12 months",
      "Online + campus immersion",
      "Institute certificate",
      "Limited / networking",
      "[INSERT]",
    ],
    [
      "Offline classroom institutes",
      "₹40,000–₹2,50,000 + living costs",
      "3–12 months",
      "In-person",
      "Provider certificate",
      "Varies by centre",
      "[INSERT]",
    ],
    [
      "Full online degrees (e.g., IIT Madras BS)",
      "₹XX,XXX–₹X,XX,XXX [VERIFY]",
      "3–4 years",
      "Online",
      "Degree",
      "Institute placement cell",
      "[INSERT]",
    ],
  ],
};

export const table2 = {
  headers: [
    "Course / Program",
    "Provider",
    "Fee (₹)",
    "EMI",
    "Duration",
    "Eligibility",
    "Format",
    "Curriculum Scope (ML / DL / GenAI / Agents / MLOps)",
    "Placement or Job Assistance",
    "Career Value Summary",
    "Verified On",
  ],
  rows: [
    [
      "AI/ML courses (multiple)",
      "NPTEL / SWAYAM",
      "₹0 (exam certificate fee extra [VERIFY])",
      "N/A",
      "4–12 weeks each",
      "Open to all",
      "Self-paced online",
      "ML Covered · DL Partial · GenAI Partial · Agents Not covered · MLOps Not covered",
      "None",
      "Academic foundations at zero fee",
      "[INSERT]",
    ],
    [
      "Practical Deep Learning for Coders",
      "fast.ai",
      "₹0",
      "N/A",
      "8–10 weeks",
      "Some coding experience",
      "Self-paced online",
      "ML Partial · DL Covered · GenAI Partial · Agents Not covered · MLOps Partial",
      "None",
      "Fastest free route to building models",
      "[INSERT]",
    ],
    [
      "NLP / LLM / Agents courses",
      "Hugging Face",
      "₹0",
      "N/A",
      "4–8 weeks each",
      "Python basics",
      "Self-paced online",
      "ML Not covered · DL Partial · GenAI Covered · Agents Covered · MLOps Partial",
      "None",
      "Current GenAI stack, no hand-holding",
      "[INSERT]",
    ],
    [
      "Top AI/ML bootcamp courses (range)",
      "Udemy",
      "₹499–₹3,999 (list prices vary [VERIFY])",
      "N/A",
      "20–60 hours",
      "None",
      "Self-paced online",
      "ML Covered · DL Partial · GenAI Partial · Agents Partial · MLOps Not covered",
      "None",
      "Cheapest structured recorded content",
      "[INSERT]",
    ],
    [
      "AI Essentials / Cloud ML tracks",
      "Google Cloud / Google",
      "₹0–₹30,000; exam fee separate [VERIFY]",
      "N/A",
      "4–12 weeks",
      "None to intermediate",
      "Self-paced online",
      "ML Partial · DL Partial · GenAI Covered · Agents Partial · MLOps Covered",
      "None",
      "Cloud-role alignment and HR-recognised badges",
      "[INSERT]",
    ],
    [
      "AWS Certified Machine Learning",
      "AWS",
      "Exam fee ₹XX,XXX [VERIFY]; training ₹0–₹25,000",
      "N/A",
      "6–12 weeks",
      "AWS experience recommended",
      "Self-paced online",
      "ML Covered · DL Partial · GenAI Partial · Agents Not covered · MLOps Covered",
      "None",
      "Signals production ML on AWS",
      "[INSERT]",
    ],
    [
      "Azure AI Engineer (AI-102)",
      "Microsoft",
      "Exam fee ₹XX,XXX [VERIFY]",
      "N/A",
      "4–10 weeks",
      "Azure basics",
      "Self-paced online",
      "ML Partial · DL Partial · GenAI Covered · Agents Partial · MLOps Covered",
      "None",
      "Enterprise Azure AI roles",
      "[INSERT]",
    ],
    [
      "Deep Learning Institute certifications",
      "NVIDIA",
      "₹0–₹XX,XXX [VERIFY]",
      "N/A",
      "1–8 weeks",
      "Python + ML basics",
      "Self-paced / workshop",
      "ML Partial · DL Covered · GenAI Covered · Agents Partial · MLOps Partial",
      "None",
      "GPU and inference specialisation",
      "[INSERT]",
    ],
    [
      "Deep Learning / ML Specializations",
      "DeepLearning.AI (Coursera)",
      "Subscription ₹X,XXX/month [VERIFY]",
      "N/A",
      "3–6 months",
      "Python, basic maths",
      "Self-paced online",
      "ML Covered · DL Covered · GenAI Covered · Agents Partial · MLOps Partial",
      "None",
      "Best-regarded conceptual grounding",
      "[INSERT]",
    ],
    [
      "AI Engineering Professional Certificate",
      "IBM (Coursera)",
      "Subscription ₹X,XXX/month [VERIFY]",
      "N/A",
      "4–6 months",
      "None stated",
      "Self-paced online",
      "ML Covered · DL Covered · GenAI Partial · Agents Not covered · MLOps Partial",
      "None",
      "Entry-level portfolio + brand certificate",
      "[INSERT]",
    ],
    [
      "AI & Machine Learning",
      "GUVI",
      "₹XX,XXX [VERIFY]",
      "Yes [VERIFY]",
      "5–9 months",
      "Graduation / final year",
      "Hybrid",
      "ML Covered · DL Covered · GenAI Partial · Agents Partial · MLOps Partial",
      "Placement support [VERIFY]",
      "Budget structured path for students",
      "[INSERT]",
    ],
    [
      "Data Science with Generative AI",
      "PW Skills",
      "₹XX,XXX [VERIFY]",
      "Yes [VERIFY]",
      "6–12 months",
      "Graduation / final year",
      "Live + recorded",
      "ML Covered · DL Covered · GenAI Covered · Agents Partial · MLOps Partial",
      "Job assistance [VERIFY]",
      "Low fee with cohort structure",
      "[INSERT]",
    ],
    [
      "BlackBelt AI program",
      "Analytics Vidhya",
      "₹XX,XXX–₹X,XX,XXX [VERIFY]",
      "Yes [VERIFY]",
      "9–12 months",
      "Graduation",
      "Live online",
      "ML Covered · DL Covered · GenAI Covered · Agents Partial · MLOps Covered",
      "Mentorship + career support [VERIFY]",
      "Community-heavy applied track",
      "[INSERT]",
    ],
    [
      "Full Stack Data Science / AI",
      "iNeuron",
      "₹XX,XXX [VERIFY]",
      "Yes [VERIFY]",
      "6–12 months",
      "Graduation",
      "Live + recorded",
      "ML Covered · DL Covered · GenAI Partial · Agents Partial · MLOps Covered",
      "Job assistance [VERIFY]",
      "Deployment-oriented on a small budget",
      "[INSERT]",
    ],
    [
      "AI Programming / ML Nanodegree",
      "Udacity",
      "Subscription ₹XX,XXX/month [VERIFY]",
      "N/A",
      "3–6 months",
      "Python basics",
      "Self-paced + reviews",
      "ML Covered · DL Covered · GenAI Partial · Agents Partial · MLOps Partial",
      "Career services [VERIFY]",
      "Human project review at a mid fee",
      "[INSERT]",
    ],
    [
      "LogicMojo AI & ML Course",
      "LogicMojo",
      "₹87,000 · 15% off for first 15 enrolments → ₹73,950 (GST treatment [VERIFY])",
      "Yes [VERIFY terms]",
      "[VERIFY: months]",
      "Graduation + basic aptitude; prerequisite onboarding [VERIFY]",
      "Live online cohort",
      "ML Covered · DL Covered · GenAI Covered · Agents Covered · MLOps Covered [VERIFY]",
      "Interview preparation and job assistance (not a guarantee)",
      "Full-stack AI capability without a credential premium",
      "[INSERT]",
    ],
    [
      "AI & ML program (IIT-affiliated variant)",
      "Intellipaat",
      "₹X,XX,XXX [VERIFY]",
      "Yes [VERIFY]",
      "7–11 months",
      "Graduation [VERIFY]",
      "Live online",
      "ML Covered · DL Covered · GenAI Covered · Agents Partial · MLOps Covered",
      "Career services [VERIFY]",
      "Institute-tagged certificate, mid-premium fee",
      "[INSERT]",
    ],
    [
      "PGP in AI & ML (Purdue / IBM)",
      "Simplilearn",
      "₹X,XX,XXX [VERIFY]",
      "Yes [VERIFY]",
      "11–12 months",
      "Graduation, 50% marks [VERIFY]",
      "Live online",
      "ML Covered · DL Covered · GenAI Covered · Agents Partial · MLOps Partial",
      "Career assistance [VERIFY]",
      "Brand credential for HR filters",
      "[INSERT]",
    ],
    [
      "PGP-AIML (UT Austin)",
      "Great Learning",
      "₹X,XX,XXX [VERIFY]",
      "Yes [VERIFY]",
      "7–12 months",
      "Graduation [VERIFY]",
      "Live online / hybrid",
      "ML Covered · DL Covered · GenAI Partial · Agents Partial · MLOps Partial",
      "Career services [VERIFY]",
      "International university tag",
      "[INSERT]",
    ],
    [
      "PG Programme in ML & AI (IIIT-Bangalore)",
      "upGrad",
      "₹X,XX,XXX [VERIFY]",
      "Yes [VERIFY]",
      "12–18 months",
      "Graduation, 50% marks [VERIFY]",
      "Online + immersion",
      "ML Covered · DL Covered · GenAI Partial · Agents Partial · MLOps Partial",
      "Career services, referrals [VERIFY]",
      "Indian university credential, long format",
      "[INSERT]",
    ],
    [
      "BS in Data Science and Applications",
      "IIT Madras",
      "₹X,XX,XXX total [VERIFY]",
      "Term-wise payment [VERIFY]",
      "3–4 years",
      "12th pass + qualifier [VERIFY]",
      "Online",
      "ML Covered · DL Covered · GenAI Partial · Agents Not covered · MLOps Partial",
      "Institute placement cell [VERIFY]",
      "A real degree, priced per term",
      "[INSERT]",
    ],
    [
      "Advanced AI/ML executive program",
      "IISc / TalentSprint",
      "₹X,XX,XXX [VERIFY]",
      "Yes [VERIFY]",
      "10–12 months",
      "Work experience [VERIFY]",
      "Online + campus visits",
      "ML Covered · DL Covered · GenAI Partial · Agents Partial · MLOps Partial",
      "Networking, limited placement",
      "Prestige and peer network",
      "[INSERT]",
    ],
    [
      "Executive AI/ML certificate programmes",
      "IIT Roorkee / IIT Delhi CCE [VERIFY names]",
      "₹X,XX,XXX [VERIFY]",
      "Yes [VERIFY]",
      "6–12 months",
      "Graduation + experience [VERIFY]",
      "Online + immersion",
      "ML Covered · DL Partial · GenAI Partial · Agents Not covered · MLOps Partial",
      "Limited",
      "Institute certificate for internal mobility",
      "[INSERT]",
    ],
    [
      "Executive AI / analytics programmes",
      "IIM (various) [VERIFY]",
      "₹X,XX,XXX [VERIFY]",
      "Yes [VERIFY]",
      "6–12 months",
      "Managerial experience [VERIFY]",
      "Online + campus",
      "ML Partial · DL Not covered · GenAI Partial · Agents Not covered · MLOps Not covered",
      "Networking",
      "AI strategy for leaders, not engineering",
      "[INSERT]",
    ],
    [
      "DS / ML / AI program",
      "Scaler",
      "₹X,XX,XXX–₹X,XX,XXX [VERIFY]",
      "Yes [VERIFY]",
      "9–18 months",
      "Coding experience / test [VERIFY]",
      "Live online cohort",
      "ML Covered · DL Covered · GenAI Covered · Agents Partial · MLOps Covered",
      "Placement operations [VERIFY]",
      "Placement infrastructure at the top of the market",
      "[INSERT]",
    ],
  ],
};

export const table3 = {
  headers: [
    "Program",
    "Fee (₹)",
    "Duration (months)",
    "Stated Weekly Hours",
    "Approx. Total Hours",
    "Cost per Month (₹)",
    "Cost per Instruction Hour (₹)",
    "Notes",
  ],
  rows: [
    [
      "NPTEL AI/ML course",
      "0",
      "3",
      "5",
      "~60",
      "0",
      "0",
      "Certificate exam fee extra [VERIFY]",
    ],
    [
      "Udemy AI/ML bootcamp",
      "~1,500 [VERIFY]",
      "Self-paced",
      "[NOT PUBLISHED]",
      "~40 recorded",
      "[NOT PUBLISHED]",
      "~38 (recorded)",
      "Recorded hours are not comparable to live hours",
    ],
    [
      "IBM AI Engineering (Coursera)",
      "Subscription [VERIFY]",
      "5",
      "6",
      "~120",
      "[VERIFY]",
      "[VERIFY]",
      "Cost depends on how fast you finish",
    ],
    [
      "PW Skills / GUVI band",
      "₹XX,XXX [VERIFY]",
      "8",
      "8–10",
      "~280",
      "[VERIFY]",
      "[VERIFY]",
      "Mix of live and recorded",
    ],
    [
      "LogicMojo AI & ML Course",
      "87,000",
      "[VERIFY: months]",
      "[VERIFY]",
      "[VERIFY]",
      "[VERIFY — compute from published duration]",
      "[VERIFY — compute from published hours]",
      "Live cohort with mentor support",
    ],
    [
      "LogicMojo AI & ML Course (offer price)",
      "73,950",
      "[VERIFY: months]",
      "[VERIFY]",
      "[VERIFY]",
      "[VERIFY]",
      "[VERIFY]",
      "15% off, first 15 enrolments",
    ],
    [
      "University PGP band",
      "₹2,00,000 [ILLUSTRATIVE mid-band]",
      "12",
      "10",
      "~480",
      "~16,667",
      "~417",
      "Includes credential and career services",
    ],
    [
      "Premium bootcamp band",
      "₹3,50,000 [ILLUSTRATIVE mid-band]",
      "12",
      "15",
      "~720",
      "~29,167",
      "~486",
      "Fee includes placement operations",
    ],
    [
      "IIT/IIM executive program",
      "₹3,00,000 [ILLUSTRATIVE mid-band]",
      "9",
      "6",
      "~216",
      "~33,333",
      "~1,389",
      "Highest cost per hour; buys network and brand",
    ],
  ],
};

export const table4 = {
  headers: [
    "Program",
    "Headline Fee (₹)",
    "EMI Available",
    "No-Cost EMI",
    "Typical EMI Tenure",
    "Lender Type [VERIFY]",
    "Current Discount / Offer",
    "Refund Window",
    "Deferral / Pause",
    "Verified On",
  ],
  rows: [
    ["NPTEL / free stack", "0", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "[INSERT]"],
    [
      "Coursera / Udemy",
      "Subscription or ₹499+ [VERIFY]",
      "Card EMI on some plans [VERIFY]",
      "[VERIFY]",
      "3–6 months",
      "Bank card EMI",
      "Frequent seasonal pricing",
      "Platform refund window [VERIFY]",
      "Cancel subscription anytime",
      "[INSERT]",
    ],
    [
      "GUVI / PW Skills band",
      "₹XX,XXX [VERIFY]",
      "Yes [VERIFY]",
      "[VERIFY]",
      "6–12 months",
      "NBFC / provider [VERIFY]",
      "[VERIFY]",
      "[VERIFY]",
      "[VERIFY]",
      "[INSERT]",
    ],
    [
      "LogicMojo AI & ML Course",
      "87,000",
      "Yes [VERIFY terms]",
      "[VERIFY]",
      "[VERIFY]",
      "[VERIFY]",
      "15% off for the first 15 enrolments → ₹73,950",
      "[VERIFY — see Refund Policy page]",
      "[VERIFY]",
      "[INSERT]",
    ],
    [
      "Intellipaat / Simplilearn / Great Learning band",
      "₹X,XX,XXX [VERIFY]",
      "Yes [VERIFY]",
      "Advertised [VERIFY]",
      "6–24 months",
      "NBFC partners [VERIFY]",
      "Rolling discounts [VERIFY]",
      "[VERIFY]",
      "[VERIFY]",
      "[INSERT]",
    ],
    [
      "upGrad PGP band",
      "₹X,XX,XXX [VERIFY]",
      "Yes [VERIFY]",
      "Advertised [VERIFY]",
      "12–36 months",
      "NBFC / bank [VERIFY]",
      "[VERIFY]",
      "[VERIFY]",
      "Batch deferral policy [VERIFY]",
      "[INSERT]",
    ],
    [
      "Scaler / premium bootcamps",
      "₹X,XX,XXX [VERIFY]",
      "Yes [VERIFY]",
      "Advertised [VERIFY]",
      "12–36 months",
      "NBFC partners [VERIFY]",
      "[VERIFY]",
      "[VERIFY]",
      "[VERIFY]",
      "[INSERT]",
    ],
    [
      "IIT / IIM / IISc executive",
      "₹X,XX,XXX [VERIFY]",
      "Instalment schedule [VERIFY]",
      "Rarely",
      "Term-wise",
      "Institute / partner [VERIFY]",
      "Early-bird [VERIFY]",
      "Strict, often none after start [VERIFY]",
      "Rare [VERIFY]",
      "[INSERT]",
    ],
    [
      "IIT Madras BS degree",
      "₹X,XX,XXX total [VERIFY]",
      "Term-wise",
      "N/A",
      "Per term",
      "Institute",
      "Fee waivers by income slab [VERIFY]",
      "Per term rules [VERIFY]",
      "Pause between terms [VERIFY]",
      "[INSERT]",
    ],
  ],
};

export const table5 = {
  headers: [
    "Level",
    "Who It's For",
    "Typical Fee (₹)",
    "Typical Duration",
    "What It Covers",
    "What It Doesn't",
    "Example Programs",
  ],
  rows: [
    [
      "Foundation / AI literacy",
      "Managers, non-tech staff, curious professionals",
      "₹0–₹25,000",
      "4–10 weeks",
      "AI concepts, prompting, tool use, business applications",
      "Model building, code",
      "DeepLearning.AI short courses, Google AI Essentials, executive literacy tracks",
    ],
    [
      "Beginner (Python → ML)",
      "Students, career switchers",
      "₹5,000–₹60,000",
      "3–6 months",
      "Python, statistics, classical ML, first projects",
      "Deep learning depth, GenAI in production, MLOps",
      "PW Skills, GUVI, IBM (Coursera), NPTEL",
    ],
    [
      "Intermediate (ML + DL + GenAI)",
      "Working professionals with basic coding",
      "₹40,000–₹1,50,000",
      "5–9 months",
      "Full ML, deep learning, NLP/CV, LLMs, RAG, some deployment",
      "Research depth",
      "LogicMojo (₹87,000), Intellipaat, Great Learning variants",
    ],
    [
      "Advanced / full-stack AI engineering",
      "Engineers targeting AI engineer / ML engineer roles",
      "₹70,000–₹4,00,000",
      "6–18 months",
      "Above + fine-tuning, agents, MLOps, system design",
      "—",
      "LogicMojo, Scaler, upGrad PGP, premium bootcamps",
    ],
    [
      "Job-oriented / placement-focused",
      "Career switchers prioritising outcomes",
      "₹70,000–₹4,00,000",
      "6–18 months",
      "Curriculum + interview prep + placement operations",
      "Guarantees (read the fine print)",
      "LogicMojo (job assistance), Scaler, university PGPs with career services",
    ],
    [
      "Executive / leadership",
      "Senior managers, consultants",
      "₹1,50,000–₹5,00,000+",
      "3–9 months",
      "Strategy, AI adoption, case studies, networking",
      "Hands-on engineering",
      "IIM, IIT, IISc executive programs",
    ],
  ],
};

export const table6 = {
  headers: [
    "Course Type",
    "Fee Range (₹)",
    "Duration",
    "Credential",
    "Eligibility",
    "Best Used For",
    "Trade-off",
  ],
  rows: [
    [
      "Short certification (provider or vendor)",
      "₹3,000–₹40,000",
      "4–12 weeks",
      "Provider / vendor certificate",
      "Usually none",
      "Skill top-up, HR checkbox, cloud-role alignment",
      "Little depth or human feedback",
    ],
    [
      "Specialist AI/ML program",
      "₹40,000–₹1,20,000",
      "5–9 months",
      "Provider certificate",
      "Graduation + basic aptitude; onboarding for prerequisites",
      "Capability-first upskilling and career switch",
      "No university tag",
    ],
    [
      "Bootcamp",
      "₹50,000–₹4,00,000",
      "6–18 months",
      "Provider certificate",
      "Aptitude test / interview at the premium end",
      "Placement infrastructure, cohort intensity",
      "High commitment and high fee at the top end",
    ],
    [
      "University-affiliated PG certificate",
      "₹1,50,000–₹3,50,000",
      "7–18 months",
      "University PG certificate",
      "Graduation, often 50% marks [VERIFY per program]",
      "Credential-driven mobility",
      "Slower curriculum refresh; premium for brand",
    ],
    [
      "Online degree",
      "₹XX,XXX–₹X,XX,XXX [VERIFY]",
      "3–4 years",
      "Degree",
      "12th pass + qualifier [VERIFY]",
      "Formal qualification",
      "Multi-year commitment",
    ],
    [
      "Executive program (IIT/IIM/IISc)",
      "₹1,50,000–₹5,00,000+",
      "3–9 months",
      "Institute certificate",
      "Work experience (often 2–5+ yrs)",
      "Leadership, networking, prestige",
      "Low hands-on depth per rupee",
    ],
  ],
};

export const table7 = {
  headers: [
    "Cost Component",
    "Online (Live Cohort)",
    "Online (Self-Paced)",
    "Offline (Classroom, Metro City)",
    "Hybrid",
  ],
  rows: [
    ["Course fee (₹)", "₹40K–₹4L", "₹0–₹40K", "₹40K–₹2.5L", "₹60K–₹3L"],
    [
      "Accommodation if relocating (per month)",
      "₹0",
      "₹0",
      "₹8,000–₹25,000 [VERIFY]",
      "Partial",
    ],
    ["Commute (per month)", "₹0", "₹0", "₹1,500–₹5,000 [VERIFY]", "Partial"],
    [
      "Lost income (career break)",
      "Usually none — evening/weekend batches",
      "None",
      "Often significant if full-time",
      "Varies",
    ],
    [
      "Hardware / cloud credits",
      "₹0–₹10,000",
      "₹0–₹10,000",
      "Often lab-provided",
      "Varies",
    ],
    [
      "Typical total, 6 months [ILLUSTRATIVE]",
      "₹45,000–₹4,10,000",
      "₹0–₹50,000",
      "₹1,00,000–₹4,30,000",
      "₹65,000–₹3,40,000",
    ],
  ],
};

export const table8 = {
  headers: [
    "Program Type",
    "Stated Duration",
    "Weekly Hours Expected",
    "Realistic at 6 hrs/week",
    "Realistic at 10 hrs/week",
    "Realistic at 15 hrs/week",
  ],
  rows: [
    ["Short certification (self-paced)", "4–12 weeks", "5–8", "3–5 months", "2–3 months", "6–8 weeks"],
    ["Vendor certification path", "4–12 weeks", "6–10", "4 months", "2.5 months", "6 weeks"],
    [
      "Specialist AI/ML program (live cohort)",
      "5–9 months",
      "10–15",
      "Not advisable — you will fall behind the cohort",
      "Roughly as stated",
      "As stated, with time for projects",
    ],
    ["Bootcamp", "6–18 months", "12–20", "Not viable", "Extends by 30–50%", "As stated"],
    ["University PG certificate", "7–18 months", "8–12", "Extends by ~30%", "As stated", "As stated"],
    ["Online degree", "3–4 years", "10–20", "5+ years", "4 years", "3–4 years"],
    ["Executive program", "3–9 months", "4–8", "As stated", "As stated", "As stated"],
    [
      "Self-paced \"3-month\" course",
      "3 months",
      "10 (assumed)",
      "6–9 months in practice",
      "4–5 months",
      "3 months",
    ],
  ],
};

export const table9 = {
  headers: [
    "Program",
    "Minimum Education",
    "Coding Prerequisite",
    "Maths Prerequisite",
    "Work Experience",
    "Entrance Test / Interview",
    "Bridge / Onboarding Module",
    "Non-Tech Friendly",
  ],
  rows: [
    ["NPTEL / SWAYAM", "None stated", "Varies by course", "Course-dependent", "None", "No (exam optional)", "No", "Partly"],
    ["Udemy / Coursera courses", "None", "Usually Python basics", "Basic", "None", "No", "Sometimes", "Yes"],
    ["Google / AWS / Azure certifications", "None stated", "Recommended", "Basic", "Recommended", "Proctored exam", "No", "Partly"],
    ["IBM AI Engineering (Coursera)", "None stated", "Python taught in-track", "Basic", "None", "No", "Yes", "Yes"],
    ["PW Skills / GUVI", "Graduation or final year [VERIFY]", "Not mandatory [VERIFY]", "Basic", "None", "No [VERIFY]", "Yes [VERIFY]", "Yes"],
    ["Udacity Nanodegree", "None stated", "Python basics", "Basic", "None", "No", "Prerequisite course sold separately", "Partly"],
    [
      "LogicMojo AI & ML Course",
      "[VERIFY: graduation]",
      "[VERIFY: basic programming aptitude]",
      "[VERIFY: intuition-first, no advanced maths]",
      "[VERIFY: open to students and professionals]",
      "[VERIFY]",
      "[VERIFY: Python and maths onboarding]",
      "[VERIFY]",
    ],
    ["Intellipaat AI & ML", "Graduation [VERIFY]", "[VERIFY]", "[VERIFY]", "Preferred [VERIFY]", "[VERIFY]", "[VERIFY]", "[VERIFY]"],
    ["Simplilearn PGP", "Graduation, 50% marks [VERIFY]", "Basic [VERIFY]", "Basic [VERIFY]", "Preferred [VERIFY]", "No [VERIFY]", "Yes [VERIFY]", "Yes [VERIFY]"],
    ["Great Learning PGP-AIML", "Graduation [VERIFY]", "Basic [VERIFY]", "Basic [VERIFY]", "Preferred [VERIFY]", "Application review [VERIFY]", "Yes [VERIFY]", "Yes [VERIFY]"],
    ["upGrad PGP (IIIT-B)", "Graduation, 50% marks [VERIFY]", "Basic [VERIFY]", "Basic [VERIFY]", "Preferred [VERIFY]", "Application review [VERIFY]", "Yes [VERIFY]", "Partly [VERIFY]"],
    ["IIT Madras BS", "12th pass [VERIFY]", "None", "12th-level maths [VERIFY]", "None", "Qualifier exam [VERIFY]", "Foundation level", "Yes"],
    ["IISc / TalentSprint", "Graduation [VERIFY]", "Yes [VERIFY]", "Yes [VERIFY]", "Often 2+ yrs [VERIFY]", "Selection process [VERIFY]", "[VERIFY]", "No [VERIFY]"],
    ["IIT / IIM executive", "Graduation [VERIFY]", "Varies", "Varies", "Often 2–5+ yrs [VERIFY]", "Application review [VERIFY]", "Rarely", "Yes (strategy tracks)"],
    ["Scaler", "Graduation [VERIFY]", "Yes [VERIFY]", "Basic [VERIFY]", "Preferred [VERIFY]", "Entrance test [VERIFY]", "[VERIFY]", "No [VERIFY]"],
  ],
};

export const table10 = {
  headers: [
    "Program",
    "Python / ML Foundations",
    "Deep Learning",
    "NLP / CV",
    "LLM Fundamentals",
    "RAG",
    "Fine-tuning",
    "Agents & Frameworks",
    "MCP / Tooling",
    "MLOps & Deployment",
    "Interview Prep",
    "Job Assistance",
    "Fee (₹)",
  ],
  rows: [
    ["NPTEL / free stack", "Good", "Good", "Good", "Partial", "Partial", "Partial", "Partial", "Not covered", "Partial", "Not covered", "Not covered", "0"],
    ["Udemy courses", "Good", "Partial", "Partial", "Partial", "Partial", "Not covered", "Partial", "Not covered", "Not covered", "Not covered", "Not covered", "~1,500 [VERIFY]"],
    ["Vendor certifications", "Partial", "Partial", "Partial", "Good", "Partial", "Partial", "Partial", "[VERIFY]", "Good", "Not covered", "Not covered", "0–30,000"],
    ["IBM AI Engineering", "Good", "Good", "Good", "Partial", "Partial", "Not covered", "Not covered", "Not covered", "Partial", "Not covered", "Not covered", "Subscription [VERIFY]"],
    ["DeepLearning.AI", "Deep", "Deep", "Good", "Good", "Good", "Partial", "Partial", "Partial", "Partial", "Not covered", "Not covered", "Subscription [VERIFY]"],
    ["PW Skills", "Good", "Good", "Partial", "Good", "Partial", "Partial", "Partial", "[VERIFY]", "Partial", "Partial", "Partial", "XX,XXX [VERIFY]"],
    ["GUVI", "Good", "Good", "Partial", "Partial", "Partial", "[VERIFY]", "[VERIFY]", "[VERIFY]", "Partial", "Partial", "Partial", "XX,XXX [VERIFY]"],
    ["Udacity", "Good", "Good", "Good", "Partial", "Partial", "Partial", "Partial", "[VERIFY]", "Partial", "Partial", "Partial", "XX,XXX [VERIFY]"],
    ["LogicMojo AI & ML Course", "Deep [VERIFY]", "Deep [VERIFY]", "Good [VERIFY]", "Deep [VERIFY]", "Good [VERIFY]", "Good [VERIFY]", "Good [VERIFY]", "[VERIFY]", "Good [VERIFY]", "Deep [VERIFY]", "Good [VERIFY]", "87,000 / 73,950"],
    ["Intellipaat", "Good", "Good", "Good", "Good", "Partial", "Partial", "Partial", "[VERIFY]", "Good", "Good", "Good", "X,XX,XXX [VERIFY]"],
    ["Simplilearn", "Good", "Good", "Good", "Good", "Partial", "Partial", "Partial", "[VERIFY]", "Partial", "Good", "Good", "X,XX,XXX [VERIFY]"],
    ["Great Learning", "Good", "Good", "Good", "Partial", "Partial", "Partial", "Partial", "[VERIFY]", "Partial", "Good", "Good", "X,XX,XXX [VERIFY]"],
    ["upGrad", "Good", "Good", "Good", "Partial", "Partial", "Partial", "Partial", "[VERIFY]", "Partial", "Good", "Good", "X,XX,XXX [VERIFY]"],
    ["IIT Madras BS", "Deep", "Good", "Good", "Partial", "Partial", "Not covered", "Not covered", "Not covered", "Partial", "Partial", "Partial", "X,XX,XXX [VERIFY]"],
    ["IISc / IIT executive", "Good", "Good", "Partial", "Partial", "Partial", "Partial", "Not covered", "Not covered", "Partial", "Partial", "Partial", "X,XX,XXX [VERIFY]"],
    ["Scaler", "Deep", "Good", "Good", "Good", "Good", "Partial", "Partial", "[VERIFY]", "Good", "Deep", "Deep", "X,XX,XXX [VERIFY]"],
  ],
};

export const table11 = {
  headers: ["Item", "Detail"],
  rows: [
    ["Course fee", "₹87,000"],
    ["Current offer", "15% discount for the first 15 enrolments"],
    ["Discounted fee", "₹73,950"],
    ["GST treatment", "[VERIFY: inclusive / exclusive]"],
    ["EMI", "[VERIFY: availability, tenure, lender, no-cost option]"],
    ["Refund policy", "[VERIFY: window and conditions — link to Refund Policy page]"],
    ["Batch deferral", "[VERIFY]"],
    ["Bond / ISA", "[VERIFY: state \"None\" only if confirmed]"],
    [
      "Inclusions",
      "Live classes, recordings, projects, mentor support, interview preparation, job assistance [VERIFY each against the course page]",
    ],
    ["Verified on", "[INSERT DATE]"],
  ],
};

export const table12 = {
  headers: ["Your Situation", "Fit", "Why"],
  rows: [
    [
      "Working engineer (2–8 yrs), 10–15 hrs/week, wants AI engineering capability",
      "Strong fit",
      "Full-stack depth with live mentorship at a specialist-band price",
    ],
    [
      "Career switcher needing Python/maths onboarding",
      "Strong fit",
      "Prerequisite onboarding, fixed structure and job assistance in one fee",
    ],
    [
      "Student or fresher with under ₹20,000 available",
      "Consider a different band first",
      "Start with a lower-fee structured program, build basics, then upgrade",
    ],
    [
      "Needs a university or IIT credential for HR or promotion",
      "Partial fit",
      "A university credential is not part of this fee; weigh against PG programs",
    ],
    [
      "Wants AI literacy only, under 5 hrs/week",
      "Consider a different band",
      "A short literacy course is the more rational spend",
    ],
    [
      "Cannot attend live sessions at all",
      "Check batch options first",
      "The live cohort format is core to how the program works",
    ],
  ],
};

export const table13 = {
  headers: [
    "Inclusion",
    "Free / MOOC",
    "Short Cert",
    "Specialist Program (e.g., LogicMojo)",
    "Bootcamp (Premium)",
    "University PGP",
    "Executive Program",
  ],
  rows: [
    ["Live classes", "No", "Rarely", "Usually [VERIFY]", "Usually", "Usually", "Usually"],
    ["Recordings", "Usually", "Usually", "Usually [VERIFY]", "Usually", "Usually", "Sometimes"],
    ["1:1 mentor access", "No", "Rarely", "Usually [VERIFY]", "Usually", "Sometimes", "Rarely"],
    ["Human code review", "No", "Rarely", "Usually [VERIFY]", "Usually", "Sometimes", "Rarely"],
    ["Doubt-resolution channel", "Rarely", "Sometimes", "Usually [VERIFY]", "Usually", "Usually", "Sometimes"],
    ["Projects with feedback", "No", "Rarely", "Usually [VERIFY]", "Usually", "Usually", "Sometimes"],
    ["Capstone", "No", "Rarely", "Usually [VERIFY]", "Usually", "Usually", "Sometimes"],
    ["Cloud / GPU credits", "Rarely", "Rarely", "[VERIFY]", "Sometimes", "Sometimes", "Sometimes"],
    ["Certificate", "Sometimes (paid)", "Usually", "Usually [VERIFY]", "Usually", "Usually", "Usually"],
    ["Interview preparation", "No", "Rarely", "Usually [VERIFY]", "Usually", "Sometimes", "Rarely"],
    ["Job assistance / placement support", "No", "Rarely", "Usually [VERIFY]", "Usually", "Usually", "Rarely"],
    ["Alumni network", "No", "Rarely", "Sometimes [VERIFY]", "Usually", "Usually", "Usually"],
    ["Campus immersion", "No", "No", "No", "Sometimes", "Sometimes", "Usually"],
  ],
};

export const table14 = {
  headers: [
    "Role",
    "Core Skills",
    "Entry Bar",
    "Fresher Range (₹ LPA)",
    "2–5 yrs Range (₹ LPA)",
    "5+ yrs Range (₹ LPA)",
    "Fee Band That Typically Prepares For This",
    "Source / Verified On",
  ],
  rows: [
    ["Data Analyst (AI-augmented)", "SQL, Python, BI tools, prompting", "Low", "[VERIFY]", "[VERIFY]", "[VERIFY]", "₹0–₹60,000", "[VERIFY: salary source] / [INSERT]"],
    ["Data Scientist", "Statistics, ML, experimentation, storytelling", "Medium", "[VERIFY]", "[VERIFY]", "[VERIFY]", "₹40,000–₹2,50,000", "[VERIFY] / [INSERT]"],
    ["ML Engineer", "ML, software engineering, pipelines, serving", "Medium-High", "[VERIFY]", "[VERIFY]", "[VERIFY]", "₹70,000–₹4,00,000", "[VERIFY] / [INSERT]"],
    ["AI Engineer", "LLM APIs, RAG, evaluation, app engineering", "Medium", "[VERIFY]", "[VERIFY]", "[VERIFY]", "₹40,000–₹1,20,000+", "[VERIFY] / [INSERT]"],
    ["GenAI / LLM Engineer", "Prompting, fine-tuning, LoRA, evals, guardrails", "Medium-High", "[VERIFY]", "[VERIFY]", "[VERIFY]", "₹70,000–₹4,00,000", "[VERIFY] / [INSERT]"],
    ["AI Agent Developer", "LangGraph, tool calling, MCP, orchestration", "Medium-High", "[VERIFY]", "[VERIFY]", "[VERIFY]", "₹40,000–₹1,20,000+", "[VERIFY] / [INSERT]"],
    ["NLP Engineer", "Transformers, tokenisation, IR, fine-tuning", "High", "[VERIFY]", "[VERIFY]", "[VERIFY]", "₹70,000+", "[VERIFY] / [INSERT]"],
    ["Computer Vision Engineer", "CNNs, detection, segmentation, edge inference", "High", "[VERIFY]", "[VERIFY]", "[VERIFY]", "₹70,000+", "[VERIFY] / [INSERT]"],
    ["MLOps Engineer", "Docker, CI/CD, monitoring, feature stores, cloud", "Medium-High", "[VERIFY]", "[VERIFY]", "[VERIFY]", "₹40,000–₹2,50,000", "[VERIFY] / [INSERT]"],
    ["AI Product Manager", "Problem framing, evals, metrics, delivery", "Medium", "[VERIFY]", "[VERIFY]", "[VERIFY]", "₹0–₹5,00,000 (executive)", "[VERIFY] / [INSERT]"],
    ["AI Consultant / Architect", "Solution design, cost modelling, governance", "High", "[VERIFY]", "[VERIFY]", "[VERIFY]", "₹1,50,000–₹5,00,000+", "[VERIFY] / [INSERT]"],
  ],
};

export const table15 = {
  headers: [
    "Fee Band (₹)",
    "Realistic Capability Reached",
    "Roles Realistically Accessible",
    "What's Missing for the Next Step",
  ],
  rows: [
    [
      "₹0",
      "Concepts plus notebook-level models, if you finish",
      "Internships, analyst support roles (with a strong portfolio)",
      "Structure, code review, deployment practice, interview preparation",
    ],
    [
      "₹500–₹5,000",
      "Guided project replication",
      "Internal projects at your current job",
      "Independent problem framing, evaluation rigour",
    ],
    [
      "₹5,000–₹40,000",
      "Working ML foundations",
      "Data analyst, junior data science support",
      "Deep learning depth, GenAI production skills, mentorship",
    ],
    [
      "₹40,000–₹1,20,000",
      "Full-stack builder: ML, DL, GenAI, RAG, agents, deployment",
      "AI engineer, ML engineer, data scientist, GenAI developer",
      "A university credential, if your employer's HR requires one",
    ],
    [
      "₹1,20,000–₹2,50,000",
      "Similar capability plus a recognised credential",
      "The same roles, plus internal promotion cases",
      "Newest-stack depth in some programs; portfolio still on you",
    ],
    [
      "₹2,50,000–₹5,00,000+",
      "Capability plus placement operations or an elite network",
      "Interview volume via placement teams, or leadership roles",
      "Nothing you can buy — completion and application effort remain yours",
    ],
  ],
};

export const table16 = {
  headers: [
    "Program",
    "Fee (₹)",
    "Capability Reached",
    "Support Depth",
    "Career Support",
    "Completion Structure",
    "Value-for-Money Read",
  ],
  rows: [
    ["NPTEL / fast.ai / Hugging Face", "0", "Foundation → Builder", "None", "None", "Self-paced", "High for self-directed learners"],
    ["Udemy course", "~1,500 [VERIFY]", "Foundation", "None", "None", "Self-paced", "High for targeted top-ups"],
    ["IBM / DeepLearning.AI (Coursera)", "Subscription [VERIFY]", "Foundation → Builder", "Low", "None", "Self-paced", "High for disciplined beginners"],
    ["PW Skills / GUVI", "₹XX,XXX [VERIFY]", "Builder", "Moderate", "Some", "Cohort + recorded", "High for budget-constrained students"],
    ["Udacity Nanodegree", "₹XX,XXX [VERIFY]", "Builder", "Moderate (project reviews)", "Limited", "Self-paced", "High for learners who need feedback, not schedules"],
    ["LogicMojo AI & ML Course", "87,000 / 73,950", "Engineer [VERIFY curriculum]", "High (live mentorship) [VERIFY]", "Interview prep + job assistance", "Live cohort", "High for structure-dependent professionals"],
    ["Intellipaat / Simplilearn / Great Learning", "₹X,XX,XXX [VERIFY]", "Builder → Engineer", "Moderate–High", "Career services", "Live cohort", "High for credential-driven buyers"],
    ["upGrad PGP (IIIT-B)", "₹X,XX,XXX [VERIFY]", "Builder → Engineer", "Moderate", "Career services", "Long cohort", "High where an Indian university tag matters"],
    ["IIT Madras BS", "₹X,XX,XXX [VERIFY]", "Engineer (over years)", "Moderate", "Placement cell", "Term-based degree", "High for learners who need a degree"],
    ["IISc / IIT / IIM executive", "₹X,XX,XXX [VERIFY]", "Foundation → Builder (strategy-led)", "Low–Moderate", "Networking", "Cohort", "High for employer-funded leaders"],
    ["Scaler", "₹X,XX,XXX [VERIFY]", "Engineer", "High", "Placement operations", "Long cohort", "High for placement-first buyers"],
  ],
};

export const checklist = [
  "Ask for the total payable figure in writing: fee, GST treatment, EMI interest, processing fee, any add-on placement tier.",
  "Ask for the syllabus with dates of last revision. If GenAI, RAG, agents and MLOps aren't in it, you're buying 2023.",
  "Ask how many live hours you get, who teaches them, and whether the same person reviews your code.",
  "Ask for the refund policy document and the lender's loan agreement — two separate documents, both binding.",
  "Ask what \"placement assistance\" includes item by item: mock interviews, referrals, resume review, company list.",
  "Ask for placement statistics with a denominator: how many enrolled, how many completed, how many were placed, over what period.",
  "Ask whether the certificate is issued by the provider or the named university, and what exactly appears on it.",
  "Ask about batch deferral: if a work crisis hits in month three, can you pause without losing the fee?",
  "Ask how projects are assessed and whether you keep the code in a public repository.",
  "Ask about cloud and API costs for GenAI projects — who pays for tokens and GPUs.",
  "Check the weekly hours honestly against your calendar for the next six months, not against your motivation today.",
  "Sit with the price for 24 hours. Any offer that cannot survive a day of thought is a sales tactic, not a discount.",
];
