import { useRef } from "react";
import { ArrowLeft, ArrowRight, Linkedin, UserRound } from "lucide-react";

import { Button } from "@/components/ui/button";

const reviewers = [
  { role: "AI hiring manager at a GCC", review: "Career scope and salary section", bio: "[INSERT: 40–60 word biography covering applied-AI hiring responsibility, years of experience and permission to publish this profile.]", quote: "[INSERT: approved, attributable quote on how Indian employers should evaluate course-led portfolios and realistic return on fees.]" },
  { role: "EdTech finance / lending specialist", review: "EMI, no-cost EMI and refunds", bio: "[INSERT: 40–60 word biography covering education-finance, consumer-credit or compliance experience and permission to publish.]", quote: "[INSERT: approved, attributable quote on comparing upfront prices, total instalments and the loan obligation after withdrawal.]" },
  { role: "Online AI program alumnus and career switcher", review: "ROI scenarios", bio: "[INSERT: 40–60 word biography covering prior background, completed program, transition timeline and permission to publish.]", quote: "[INSERT: approved, attributable quote on completion, portfolio work and the non-fee costs of changing careers.]" },
  { role: "AI curriculum designer", review: "Curriculum-scope tables", bio: "[INSERT: 40–60 word biography covering ML, GenAI, RAG, agent and MLOps curriculum work and permission to publish.]", quote: "[INSERT: approved, attributable quote on distinguishing a current applied syllabus from a dated module list.]" },
];

export function AuthorProfile() {
  return <div className="profile-card"><div className="profile-photo"><UserRound aria-hidden="true" /><span>Photo placeholder</span></div><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Independent methodology record</p><h3 className="mt-3 text-2xl font-semibold">[INSERT: Author name]</h3><p className="mt-1 font-semibold text-muted-foreground">[INSERT: Role] — AI education analyst and fee/curriculum reviewer</p><p className="mt-4 leading-relaxed">[INSERT: 60–90 word biography describing the actual public-fee collection process, fine-print review, source recording and quarterly verification cadence. Publish only after the named author confirms this methodology was followed.]</p><div className="mt-5 flex flex-wrap gap-4 text-sm"><a href="#author" className="inline-flex items-center gap-2 font-semibold text-primary"><Linkedin /> LinkedIn [INSERT URL]</a><span className="text-muted-foreground">Last reviewed: [INSERT DATE]</span></div><p className="mt-4 text-sm text-muted-foreground">Fees and active offers are scheduled for re-verification quarterly and before each republish.</p></div></div>;
}

export function ReviewerCarousel() {
  const ref = useRef<HTMLDivElement>(null);
  const move = (direction: number) => ref.current?.scrollBy({ left: direction * 390, behavior: "smooth" });
  return <div><div className="mb-5 grid grid-cols-[minmax(0,1fr)_auto] items-end gap-4"><p className="m-0 max-w-2xl text-sm text-muted-foreground">Four specialist review slots are preserved below. Names, affiliations and quotes remain explicit placeholders until permission and review are documented.</p><div className="flex gap-2"><Button type="button" size="icon" variant="outline" aria-label="Previous reviewer" onClick={() => move(-1)}><ArrowLeft /></Button><Button type="button" size="icon" variant="outline" aria-label="Next reviewer" onClick={() => move(1)}><ArrowRight /></Button></div></div><div ref={ref} className="reviewer-track">{reviewers.map((r, i) => <article key={r.role} className="reviewer-card"><div className="flex items-start gap-4"><div className="reviewer-avatar"><UserRound aria-hidden="true" /></div><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">Reviewer {i + 1}</p><h3 className="mt-1 text-lg font-semibold">[INSERT: Name]</h3><p className="text-sm text-muted-foreground">{r.role} · [INSERT: Company]</p></div></div><p className="mt-5 text-sm leading-relaxed">{r.bio}</p><blockquote className="mt-5 border-l-2 border-primary pl-4 text-sm italic leading-relaxed text-foreground">“{r.quote}”</blockquote><p className="mt-5 text-xs font-semibold text-muted-foreground">Reviewed: {r.review}</p><a href="#expert-reviewers" className="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-primary"><Linkedin /> LinkedIn [INSERT URL]</a></article>)}</div><p className="mt-5 rounded-md border border-highlight bg-highlight/20 px-4 py-3 text-sm text-highlight-foreground"><strong>Disclosure required before publication:</strong> [INSERT: state whether reviewers assessed accuracy and framework without compensation; otherwise disclose each affiliation and compensation arrangement.]</p></div>;
}
